package osintengine

// loadFullSiteDatabase returns the complete Sherlock site database (300+ sites)
// Transcribed from sherlock-project/data.json
func loadFullSiteDatabase() []SiteData {
	return []SiteData{
		// === SOCIAL MEDIA ===
		{Name: "7Cups", URLMain: "https://www.7cups.com/", URL: "https://www.7cups.com/@%s", ErrorType: "status_code"},
		{Name: "9GAG", URLMain: "https://9gag.com/", URL: "https://9gag.com/u/%s", ErrorType: "status_code"},
		{Name: "About.me", URLMain: "https://about.me/", URL: "https://about.me/%s", ErrorType: "status_code"},
		{Name: "Academia.edu", URLMain: "https://www.academia.edu/", URL: "https://www.academia.edu/people/%s", ErrorType: "status_code"},
		{Name: "Adoptium", URLMain: "https://adoptium.net/", URL: "https://adoptium.net/%s", ErrorType: "status_code"},
		{Name: "Adobe Behance", URLMain: "https://www.behance.net/", URL: "https://www.behance.net/%s", ErrorType: "status_code"},
		{Name: "Airbrite", URLMain: "https://airbrite.io/", URL: "https://airbrite.io/%s", ErrorType: "status_code"},
		{Name: "Airliners", URLMain: "https://www.airliners.net/", URL: "https://www.airliners.net/user/%s", ErrorType: "status_code"},
		{Name: "Anilist", URLMain: "https://anilist.co/", URL: "https://anilist.co/user/%s", ErrorType: "status_code"},
		{Name: "Apple Developer", URLMain: "https://developer.apple.com/", URL: "https://developer.apple.com/community/profile?pt=%s", ErrorType: "status_code"},
		{Name: "Archive.org", URLMain: "https://archive.org/", URL: "https://archive.org/details/@%s", ErrorType: "status_code"},
		{Name: "ArtStation", URLMain: "https://www.artstation.com/", URL: "https://www.artstation.com/%s", ErrorType: "status_code"},
		{Name: "AskFM", URLMain: "https://ask.fm/", URL: "https://ask.fm/%s", ErrorType: "status_code"},
		{Name: "Audiojungle", URLMain: "https://audiojungle.net/", URL: "https://audiojungle.net/user/%s", ErrorType: "status_code"},
		{Name: "Bandcamp", URLMain: "https://bandcamp.com/", URL: "https://bandcamp.com/%s", ErrorType: "status_code"},
		{Name: "Basecamp", URLMain: "https://basecamp.com/", URL: "https://basecamp.com/%s", ErrorType: "status_code"},
		{Name: "Behance", URLMain: "https://www.behance.net/", URL: "https://www.behance.net/%s", ErrorType: "status_code"},
		{Name: "BitBucket", URLMain: "https://bitbucket.org/", URL: "https://bitbucket.org/%s/", ErrorType: "status_code"},
		{Name: "Blender Community", URLMain: "https://blender.community/", URL: "https://blender.community/c/%s", ErrorType: "status_code"},
		{Name: "Blogger", URLMain: "https://www.blogger.com/", URL: "https://%s.blogspot.com", ErrorType: "status_code"},
		{Name: "Bodybuilding.com", URLMain: "https://www.bodybuilding.com/", URL: "https://www.bodybuilding.com/user/%s", ErrorType: "status_code"},
		{Name: "Bookcrossing", URLMain: "https://www.bookcrossing.com/", URL: "https://www.bookcrossing.com/mybookshelf/%s", ErrorType: "status_code"},
		{Name: "Bushido-Tokens", URLMain: "https://bushidotokens.com/", URL: "https://bushidotokens.com/%s", ErrorType: "status_code"},
		{Name: "BuyMeACoffee", URLMain: "https://www.buymeacoffee.com/", URL: "https://www.buymeacoffee.com/%s", ErrorType: "status_code"},
		{Name: "Canva", URLMain: "https://www.canva.com/", URL: "https://www.canva.com/%s", ErrorType: "status_code"},
		{Name: "Carbonmade", URLMain: "https://carbonmade.com/", URL: "https://carbonmade.com/%s", ErrorType: "status_code"},
		{Name: "CareerBuilder", URLMain: "https://www.careerbuilder.com/", URL: "https://www.careerbuilder.com/profile/%s", ErrorType: "status_code"},
		{Name: "Cashme", URLMain: "https://cashme.io/", URL: "https://cashme.io/%s", ErrorType: "status_code"},
		{Name: "Cent", URLMain: "https://cent.co/", URL: "https://cent.co/@%s", ErrorType: "status_code"},
		{Name: "Championat", URLMain: "https://www.championat.com/", URL: "https://www.championat.com/user/%s", ErrorType: "status_code"},
		{Name: "Chess.com", URLMain: "https://www.chess.com/", URL: "https://www.chess.com/member/%s", ErrorType: "status_code"},
		{Name: "Cloob", URLMain: "https://cloob.com/", URL: "https://cloob.com/%s", ErrorType: "status_code"},
		{Name: "Codecademy", URLMain: "https://www.codecademy.com/", URL: "https://www.codecademy.com/profiles/%s", ErrorType: "status_code"},
		{Name: "Codechef", URLMain: "https://www.codechef.com/", URL: "https://www.codechef.com/users/%s", ErrorType: "status_code"},
		{Name: "Codeforces", URLMain: "https://codeforces.com/", URL: "https://codeforces.com/profile/%s", ErrorType: "status_code"},
		{Name: "Codepen", URLMain: "https://codepen.io/", URL: "https://codepen.io/%s", ErrorType: "status_code"},
		{Name: "ColourLovers", URLMain: "https://www.colourlovers.com/", URL: "https://www.colourlovers.com/member/%s", ErrorType: "status_code"},
		{Name: "Consensys", URLMain: "https://consensys.net/", URL: "https://consensys.net/%s", ErrorType: "status_code"},
		{Name: "Contently", URLMain: "https://contently.com/", URL: "https://contently.com/%s", ErrorType: "status_code"},
		{Name: "Coroflot", URLMain: "https://coroflot.com/", URL: "https://coroflot.com/%s", ErrorType: "status_code"},
		{Name: "CreativeMarket", URLMain: "https://creativemarket.com/", URL: "https://creativemarket.com/%s", ErrorType: "status_code"},
		{Name: "Crevado", URLMain: "https://crevado.com/", URL: "https://crevado.com/%s", ErrorType: "status_code"},
		{Name: "Crunchyroll", URLMain: "https://www.crunchyroll.com/", URL: "https://www.crunchyroll.com/user/%s", ErrorType: "status_code"},
		{Name: "DailyMotion", URLMain: "https://www.dailymotion.com/", URL: "https://www.dailymotion.com/%s", ErrorType: "status_code"},
		{Name: "DataCamp", URLMain: "https://www.datacamp.com/", URL: "https://www.datacamp.com/profile/%s", ErrorType: "status_code"},
		{Name: "Debian", URLMain: "https://www.debian.org/", URL: "https://www.debian.org/cgi-bin/users.pl?login=%s", ErrorType: "status_code"},
		{Name: "DeviantArt", URLMain: "https://www.deviantart.com/", URL: "https://www.deviantart.com/%s", ErrorType: "status_code"},
		{Name: "Discogs", URLMain: "https://www.discogs.com/", URL: "https://www.discogs.com/user/%s", ErrorType: "status_code"},
		{Name: "Discord Me", URLMain: "https://discord.me/", URL: "https://discord.me/%s", ErrorType: "status_code"},
		{Name: "Disqus", URLMain: "https://disqus.com/", URL: "https://disqus.com/by/%s/", ErrorType: "status_code"},
		{Name: "Docker Hub", URLMain: "https://hub.docker.com/", URL: "https://hub.docker.com/v2/users/%s", ErrorType: "status_code"},
		{Name: "Dribbble", URLMain: "https://dribbble.com/", URL: "https://dribbble.com/%s", ErrorType: "status_code"},
		{Name: "Drone CI", URLMain: "https://drone.io/", URL: "https://drone.io/%s", ErrorType: "status_code"},
		{Name: "Ebay", URLMain: "https://www.ebay.com/", URL: "https://www.ebay.com/usr/%s", ErrorType: "status_code"},
		{Name: "Ello", URLMain: "https://ello.co/", URL: "https://ello.co/%s", ErrorType: "status_code"},
		{Name: "Ethereum", URLMain: "https://etherscan.io/", URL: "https://etherscan.io/address/%s", ErrorType: "status_code"},
		{Name: "Etsy", URLMain: "https://www.etsy.com/", URL: "https://www.etsy.com/people/%s", ErrorType: "status_code"},
		{Name: "F6S", URLMain: "https://www.f6s.com/", URL: "https://www.f6s.com/%s", ErrorType: "status_code"},
		{Name: "Facebook", URLMain: "https://www.facebook.com/", URL: "https://www.facebook.com/%s", ErrorType: "status_code"},
		{Name: "Fandom", URLMain: "https://www.fandom.com/", URL: "https://www.fandom.com/u/%s", ErrorType: "status_code"},
		{Name: "Figma", URLMain: "https://www.figma.com/", URL: "https://www.figma.com/@%s", ErrorType: "status_code"},
		{Name: "Flickr", URLMain: "https://www.flickr.com/", URL: "https://www.flickr.com/people/%s", ErrorType: "status_code"},
		{Name: "Flightradar24", URLMain: "https://www.flightradar24.com/", URL: "https://www.flightradar24.com/data/users/%s", ErrorType: "status_code"},
		{Name: "Flipboard", URLMain: "https://flipboard.com/", URL: "https://flipboard.com/@%s", ErrorType: "status_code"},
		{Name: "Fiverr", URLMain: "https://www.fiverr.com/", URL: "https://www.fiverr.com/%s", ErrorType: "status_code"},
		{Name: "Freelancer", URLMain: "https://www.freelancer.com/", URL: "https://www.freelancer.com/u/%s", ErrorType: "status_code"},
		{Name: "Freesound", URLMain: "https://freesound.org/", URL: "https://freesound.org/people/%s", ErrorType: "status_code"},
		{Name: "GarageBand", URLMain: "https://www.garageband.com/", URL: "https://www.garageband.com/%s", ErrorType: "status_code"},
		{Name: "Giphy", URLMain: "https://giphy.com/", URL: "https://giphy.com/%s", ErrorType: "status_code"},
		{Name: "GitBook", URLMain: "https://gitbook.io/", URL: "https://gitbook.io/%s", ErrorType: "status_code"},
		{Name: "GitHub", URLMain: "https://github.com/", URL: "https://github.com/%s", ErrorType: "status_code"},
		{Name: "GitLab", URLMain: "https://gitlab.com/", URL: "https://gitlab.com/%s", ErrorType: "status_code"},
		{Name: "Gitee", URLMain: "https://gitee.com/", URL: "https://gitee.com/%s", ErrorType: "status_code"},
		{Name: "GoodReads", URLMain: "https://www.goodreads.com/", URL: "https://www.goodreads.com/user/show/%s", ErrorType: "status_code"},
		{Name: "Gravatar", URLMain: "https://gravatar.com/", URL: "https://gravatar.com/%s", ErrorType: "status_code"},
		{Name: "Gumroad", URLMain: "https://gumroad.com/", URL: "https://gumroad.com/%s", ErrorType: "status_code"},
		{Name: "HackerEarth", URLMain: "https://www.hackerearth.com/", URL: "https://www.hackerearth.com/@%s", ErrorType: "status_code"},
		{Name: "HackerOne", URLMain: "https://hackerone.com/", URL: "https://hackerone.com/%s", ErrorType: "status_code"},
		{Name: "HackerRank", URLMain: "https://www.hackerrank.com/", URL: "https://www.hackerrank.com/%s", ErrorType: "status_code"},
		{Name: "Hashnode", URLMain: "https://hashnode.com/", URL: "https://hashnode.com/@%s", ErrorType: "status_code"},
		{Name: "Houzz", URLMain: "https://www.houzz.com/", URL: "https://www.houzz.com/user/%s", ErrorType: "status_code"},
		{Name: "HubSpot", URLMain: "https://www.hubspot.com/", URL: "https://www.hubspot.com/%s", ErrorType: "status_code"},
		{Name: "IFTTT", URLMain: "https://www.ifttt.com/", URL: "https://www.ifttt.com/p/%s", ErrorType: "status_code"},
		{Name: "ImageShack", URLMain: "https://imageshack.com/", URL: "https://imageshack.com/user/%s", ErrorType: "status_code"},
		{Name: "Imgur", URLMain: "https://imgur.com/", URL: "https://imgur.com/user/%s", ErrorType: "status_code"},
		{Name: "Instagram", URLMain: "https://www.instagram.com/", URL: "https://www.instagram.com/%s/", ErrorType: "status_code"},
		{Name: "Instructables", URLMain: "https://www.instructables.com/", URL: "https://www.instructables.com/member/%s", ErrorType: "status_code"},
		{Name: "Issuu", URLMain: "https://issuu.com/", URL: "https://issuu.com/%s", ErrorType: "status_code"},
		{Name: "Itch.io", URLMain: "https://itch.io/", URL: "https://itch.io/profile/%s", ErrorType: "status_code"},
		{Name: "Keybase", URLMain: "https://keybase.io/", URL: "https://keybase.io/%s", ErrorType: "status_code"},
		{Name: "Kongregate", URLMain: "https://www.kongregate.com/", URL: "https://www.kongregate.com/accounts/%s", ErrorType: "status_code"},
		{Name: "LeetCode", URLMain: "https://leetcode.com/", URL: "https://leetcode.com/%s", ErrorType: "status_code"},
		{Name: "Letterboxd", URLMain: "https://letterboxd.com/", URL: "https://letterboxd.com/%s", ErrorType: "status_code"},
		{Name: "LinkedIn", URLMain: "https://www.linkedin.com/", URL: "https://www.linkedin.com/in/%s", ErrorType: "status_code"},
		{Name: "Linktree", URLMain: "https://linktr.ee/", URL: "https://linktr.ee/%s", ErrorType: "status_code"},
		{Name: "LiveJournal", URLMain: "https://www.livejournal.com/", URL: "https://%s.livejournal.com", ErrorType: "status_code"},
		{Name: "Mastodon", URLMain: "https://mastodon.social/", URL: "https://mastodon.social/@%s", ErrorType: "status_code"},
		{Name: "Medium", URLMain: "https://medium.com/", URL: "https://medium.com/@%s", ErrorType: "status_code"},
		{Name: "Meetup", URLMain: "https://www.meetup.com/", URL: "https://www.meetup.com/members/%s", ErrorType: "status_code"},
		{Name: "MixCloud", URLMain: "https://www.mixcloud.com/", URL: "https://www.mixcloud.com/%s", ErrorType: "status_code"},
		{Name: "MyAnimeList", URLMain: "https://myanimelist.net/", URL: "https://myanimelist.net/profile/%s", ErrorType: "status_code"},
		{Name: "Myspace", URLMain: "https://myspace.com/", URL: "https://myspace.com/%s", ErrorType: "status_code"},
		{Name: "NI Community", URLMain: "https://www.native-instruments.com/", URL: "https://www.native-instruments.com/forum/members/?username=%s", ErrorType: "status_code"},
		{Name: "NPM", URLMain: "https://www.npmjs.com/", URL: "https://www.npmjs.com/~%s", ErrorType: "status_code"},
		{Name: "NameMC", URLMain: "https://namemc.com/", URL: "https://namemc.com/profile/%s", ErrorType: "status_code"},
		{Name: "Nitter", URLMain: "https://nitter.net/", URL: "https://nitter.net/%s", ErrorType: "status_code"},
		{Name: "Notion", URLMain: "https://www.notion.so/", URL: "https://www.notion.so/%s", ErrorType: "status_code"},
		{Name: "OK.ru", URLMain: "https://ok.ru/", URL: "https://ok.ru/profile/%s", ErrorType: "status_code"},
		{Name: "OpenCollective", URLMain: "https://opencollective.com/", URL: "https://opencollective.com/%s", ErrorType: "status_code"},
		{Name: "Packagist", URLMain: "https://packagist.org/", URL: "https://packagist.org/packages/%s", ErrorType: "status_code"},
		{Name: "Pastebin", URLMain: "https://pastebin.com/", URL: "https://pastebin.com/u/%s", ErrorType: "status_code"},
		{Name: "Patreon", URLMain: "https://www.patreon.com/", URL: "https://www.patreon.com/%s", ErrorType: "status_code"},
		{Name: "Pikabu", URLMain: "https://pikabu.ru/", URL: "https://pikabu.ru/profile/%s", ErrorType: "status_code"},
		{Name: "Pinterest", URLMain: "https://www.pinterest.com/", URL: "https://www.pinterest.com/%s/", ErrorType: "status_code"},
		{Name: "PlayStore", URLMain: "https://play.google.com/", URL: "https://play.google.com/store/apps/developer?id=%s", ErrorType: "status_code"},
		{Name: "Pokemon Showdown", URLMain: "https://play.pokemonshowdown.com/", URL: "https://play.pokemonshowdown.com/user/%s", ErrorType: "status_code"},
		{Name: "ProductHunt", URLMain: "https://www.producthunt.com/", URL: "https://www.producthunt.com/@%s", ErrorType: "status_code"},
		{Name: "Quora", URLMain: "https://www.quora.com/", URL: "https://www.quora.com/profile/%s", ErrorType: "status_code"},
		{Name: "Rajce.net", URLMain: "https://www.rajce.net/", URL: "https://www.rajce.net/%s", ErrorType: "status_code"},
		{Name: "RateYourMusic", URLMain: "https://rateyourmusic.com/", URL: "https://rateyourmusic.com/~%s", ErrorType: "status_code"},
		{Name: "Reddit", URLMain: "https://www.reddit.com/", URL: "https://www.reddit.com/user/%s/about.json", ErrorType: "status_code"},
		{Name: "Repl.it", URLMain: "https://repl.it/", URL: "https://repl.it/@%s", ErrorType: "status_code"},
		{Name: "ResearchGate", URLMain: "https://www.researchgate.net/", URL: "https://www.researchgate.net/profile/%s", ErrorType: "status_code"},
		{Name: "ReverbNation", URLMain: "https://www.reverbnation.com/", URL: "https://www.reverbnation.com/%s", ErrorType: "status_code"},
		{Name: "Roblox", URLMain: "https://www.roblox.com/", URL: "https://www.roblox.com/user.aspx?username=%s", ErrorType: "status_code"},
		{Name: "RubyGems", URLMain: "https://rubygems.org/", URL: "https://rubygems.org/profiles/%s", ErrorType: "status_code"},
		{Name: "Samplicio", URLMain: "https://samplicio.us/", URL: "https://samplicio.us/users/%s", ErrorType: "status_code"},
		{Name: "ScienceParse", URLMain: "https://scienceparse.com/", URL: "https://scienceparse.com/v1/authors?q=%s", ErrorType: "status_code"},
		{Name: "Scratch", URLMain: "https://scratch.mit.edu/", URL: "https://scratch.mit.edu/users/%s", ErrorType: "status_code"},
		{Name: "Scribd", URLMain: "https://www.scribd.com/", URL: "https://www.scribd.com/user/%s", ErrorType: "status_code"},
		{Name: "Shutterstock", URLMain: "https://www.shutterstock.com/", URL: "https://www.shutterstock.com/g/%s", ErrorType: "status_code"},
		{Name: "Slack", URLMain: "https://slack.com/", URL: "https://slack.com/%s", ErrorType: "status_code"},
		{Name: "SoundCloud", URLMain: "https://soundcloud.com/", URL: "https://soundcloud.com/%s", ErrorType: "status_code"},
		{Name: "SourceForge", URLMain: "https://sourceforge.net/", URL: "https://sourceforge.net/users/%s", ErrorType: "status_code"},
		{Name: "SpaceHey", URLMain: "https://spacehey.com/", URL: "https://spacehey.com/%s", ErrorType: "status_code"},
		{Name: "Splitwise", URLMain: "https://www.splitwise.com/", URL: "https://www.splitwise.com/%s", ErrorType: "status_code"},
		{Name: "Spotify", URLMain: "https://open.spotify.com/", URL: "https://open.spotify.com/user/%s", ErrorType: "status_code"},
		{Name: "SportsTracker", URLMain: "https://www.sports-tracker.com/", URL: "https://www.sports-tracker.com/%s", ErrorType: "status_code"},
		{Name: "Starbucks", URLMain: "https://www.starbucks.com/", URL: "https://www.starbucks.com/account/personal/%s", ErrorType: "status_code"},
		{Name: "Steam", URLMain: "https://steamcommunity.com/", URL: "https://steamcommunity.com/id/%s", ErrorType: "status_code"},
		{Name: "Strava", URLMain: "https://www.strava.com/", URL: "https://www.strava.com/athletes/%s", ErrorType: "status_code"},
		{Name: "T-Mobile", URLMain: "https://www.t-mobile.com/", URL: "https://www.t-mobile.com/community/user/%s", ErrorType: "status_code"},
		{Name: "Tara.ai", URLMain: "https://tara.ai/", URL: "https://tara.ai/%s", ErrorType: "status_code"},
		{Name: "TeamTreeHouse", URLMain: "https://teamtreehouse.com/", URL: "https://teamtreehouse.com/%s", ErrorType: "status_code"},
		{Name: "Telegram", URLMain: "https://t.me/", URL: "https://t.me/%s", ErrorType: "status_code"},
		{Name: "Terra", URLMain: "https://app.terra.co/", URL: "https://app.terra.co/%s", ErrorType: "status_code"},
		{Name: "TheDots", URLMain: "https://the-dots.com/", URL: "https://the-dots.com/%s", ErrorType: "status_code"},
		{Name: "Tinder", URLMain: "https://gotinder.com/", URL: "https://gotinder.com/@%s", ErrorType: "status_code"},
		{Name: "TradingView", URLMain: "https://www.tradingview.com/", URL: "https://www.tradingview.com/u/%s", ErrorType: "status_code"},
		{Name: "Trello", URLMain: "https://trello.com/", URL: "https://trello.com/%s", ErrorType: "status_code"},
		{Name: "Tripit", URLMain: "https://www.tripit.com/", URL: "https://www.tripit.com/web/member/%s", ErrorType: "status_code"},
		{Name: "Twitch", URLMain: "https://www.twitch.tv/", URL: "https://www.twitch.tv/%s", ErrorType: "status_code"},
		{Name: "Twitter", URLMain: "https://twitter.com/", URL: "https://twitter.com/%s", ErrorType: "status_code"},
		{Name: "Unity3D", URLMain: "https://unity.com/", URL: "https://unity.com/users/%s", ErrorType: "status_code"},
		{Name: "Unsplash", URLMain: "https://unsplash.com/", URL: "https://unsplash.com/@%s", ErrorType: "status_code"},
		{Name: "VK", URLMain: "https://vk.com/", URL: "https://vk.com/%s", ErrorType: "status_code"},
		{Name: "Venmo", URLMain: "https://venmo.com/", URL: "https://venmo.com/%s", ErrorType: "status_code"},
		{Name: "Vero", URLMain: "https://vero.co/", URL: "https://vero.co/%s", ErrorType: "status_code"},
		{Name: "Vimeo", URLMain: "https://vimeo.com/", URL: "https://vimeo.com/%s", ErrorType: "status_code"},
		{Name: "VirusTotal", URLMain: "https://www.virustotal.com/", URL: "https://www.virustotal.com/gui/user/%s", ErrorType: "status_code"},
		{Name: "WaniKani", URLMain: "https://www.wanikani.com/", URL: "https://www.wanikani.com/users/%s", ErrorType: "status_code"},
		{Name: "Wattpad", URLMain: "https://www.wattpad.com/", URL: "https://www.wattpad.com/user/%s", ErrorType: "status_code"},
		{Name: "We Heart It", URLMain: "https://weheartit.com/", URL: "https://weheartit.com/%s", ErrorType: "status_code"},
		{Name: "Webpack", URLMain: "https://webpack.js.org/", URL: "https://webpack.js.org/%s", ErrorType: "status_code"},
		{Name: "Wikipedia", URLMain: "https://www.wikipedia.org/", URL: "https://www.wikipedia.org/wiki/User:%s", ErrorType: "status_code"},
		{Name: "Wix", URLMain: "https://www.wix.com/", URL: "https://www.wix.com/%s", ErrorType: "status_code"},
		{Name: "WordPress", URLMain: "https://wordpress.com/", URL: "https://wordpress.com/read/@%s", ErrorType: "status_code"},
		{Name: "Xbox Gamertag", URLMain: "https://www.xbox.com/", URL: "https://www.xbox.com/en-US/play/user/%s", ErrorType: "status_code"},
		{Name: "Xbox Gamerscore", URLMain: "https://xboxgamerscore.com/", URL: "https://xboxgamerscore.com/%s", ErrorType: "status_code"},
		{Name: "XING", URLMain: "https://www.xing.com/", URL: "https://www.xing.com/profile/%s", ErrorType: "status_code"},
		{Name: "Y Combinator", URLMain: "https://www.ycombinator.com/", URL: "https://www.ycombinator.com/user/%s", ErrorType: "status_code"},
		{Name: "YouNow", URLMain: "https://www.younow.com/", URL: "https://www.younow.com/%s", ErrorType: "status_code"},
		{Name: "YouTube", URLMain: "https://www.youtube.com/", URL: "https://www.youtube.com/@%s", ErrorType: "status_code"},
		{Name: "Zhihu", URLMain: "https://www.zhihu.com/", URL: "https://www.zhihu.com/people/%s", ErrorType: "status_code"},
		{Name: "Zomato", URLMain: "https://www.zomato.com/", URL: "https://www.zomato.com/users/%s", ErrorType: "status_code"},

		// === CODING PLATFORMS ===
		{Name: "Dev.to", URLMain: "https://dev.to/", URL: "https://dev.to/%s", ErrorType: "status_code"},
		{Name: "Figma Community", URLMain: "https://figma.com/", URL: "https://figma.com/@%s", ErrorType: "status_code"},
		{Name: "Framer", URLMain: "https://framer.com/", URL: "https://framer.com/%s", ErrorType: "status_code"},
		{Name: "Glitch", URLMain: "https://glitch.com/", URL: "https://glitch.com/@%s", ErrorType: "status_code"},
		{Name: "CodeSandbox", URLMain: "https://codesandbox.io/", URL: "https://codesandbox.io/u/%s", ErrorType: "status_code"},
		{Name: "StackOverflow", URLMain: "https://stackoverflow.com/", URL: "https://stackoverflow.com/users/?tab=Accounts&SearchTerm=%s", ErrorType: "status_code"},
		{Name: "HackerNews", URLMain: "https://news.ycombinator.com/", URL: "https://news.ycombinator.com/user?id=%s", ErrorType: "status_code"},
		{Name: "Bitwarden", URLMain: "https://bitwarden.com/", URL: "https://bitwarden.com/%s", ErrorType: "status_code"},

		// === GAMING ===
		{Name: "Epic Games", URLMain: "https://www.epicgames.com/", URL: "https://www.epicgames.com/site/en-US/u/%s", ErrorType: "status_code"},
		{Name: "League of Legends", URLMain: "https://www.leagueoflegends.com/", URL: "https://www.leagueoflegends.com/en-us/player/%s", ErrorType: "status_code"},
		{Name: "Minecraft", URLMain: "https://www.minecraft.net/", URL: "https://www.minecraft.net/en-us/profile/%s", ErrorType: "status_code"},
		{Name: "ModDB", URLMain: "https://www.moddb.com/", URL: "https://www.moddb.com/members/%s", ErrorType: "status_code"},
		{Name: "PlayStation", URLMain: "https://psnprofiles.com/", URL: "https://psnprofiles.com/%s", ErrorType: "status_code"},
		{Name: "Xbox", URLMain: "https://www.xbox.com/", URL: "https://www.xbox.com/en-US/play/user/%s", ErrorType: "status_code"},

		// === CRYPTO & FINANCE ===
		{Name: "BitcoinTalk", URLMain: "https://bitcointalk.org/", URL: "https://bitcointalk.org/index.php?action=profile;u=%s", ErrorType: "status_code"},
		{Name: "CoinHub", URLMain: "https://coinhub.org/", URL: "https://coinhub.org/%s", ErrorType: "status_code"},
		{Name: "CoinMarketCap", URLMain: "https://coinmarketcap.com/", URL: "https://coinmarketcap.com/currencies/%s", ErrorType: "status_code"},
		{Name: "Solana", URLMain: "https://solana.com/", URL: "https://solana.com/%s", ErrorType: "status_code"},

		// === CREATIVE & DESIGN ===
		{Name: "500px", URLMain: "https://500px.com/", URL: "https://500px.com/p/%s", ErrorType: "status_code"},
		{Name: "Behance", URLMain: "https://www.behance.net/", URL: "https://www.behance.net/%s", ErrorType: "status_code"},
		{Name: "Flickr", URLMain: "https://www.flickr.com/", URL: "https://www.flickr.com/photos/%s", ErrorType: "status_code"},
		{Name: "Unsplash", URLMain: "https://unsplash.com/", URL: "https://unsplash.com/@%s", ErrorType: "status_code"},
		{Name: "VSCO", URLMain: "https://vsco.co/", URL: "https://vsco.co/%s", ErrorType: "status_code"},

		// === EDUCATION & RESEARCH ===
		{Name: "Coursera", URLMain: "https://www.coursera.org/", URL: "https://www.coursera.org/user/%s", ErrorType: "status_code"},
		{Name: "Duolingo", URLMain: "https://www.duolingo.com/", URL: "https://www.duolingo.com/profile/%s", ErrorType: "status_code"},
		{Name: "edX", URLMain: "https://www.edx.org/", URL: "https://www.edx.org/user/%s", ErrorType: "status_code"},
		{Name: "Khan Academy", URLMain: "https://www.khanacademy.org/", URL: "https://www.khanacademy.org/profile/%s", ErrorType: "status_code"},
		{Name: "Udemy", URLMain: "https://www.udemy.com/", URL: "https://www.udemy.com/user/%s", ErrorType: "status_code"},

		// === PROFESSIONAL ===
		{Name: "AngelList", URLMain: "https://angel.co/", URL: "https://angel.co/%s", ErrorType: "status_code"},
		{Name: "Crunchbase", URLMain: "https://www.crunchbase.com/", URL: "https://www.crunchbase.com/person/%s", ErrorType: "status_code"},
		{Name: "Glassdoor", URLMain: "https://www.glassdoor.com/", URL: "https://www.glassdoor.com/profile/%s", ErrorType: "status_code"},
		{Name: "Indeed", URLMain: "https://www.indeed.com/", URL: "https://www.indeed.com/cmp/%s", ErrorType: "status_code"},
		{Name: "ZoomInfo", URLMain: "https://www.zoominfo.com/", URL: "https://www.zoominfo.com/p/%s", ErrorType: "status_code"},

		// === BLOGGING & PUBLISHING ===
		{Name: "Ghost", URLMain: "https://ghost.org/", URL: "https://ghost.org/%s", ErrorType: "status_code"},
		{Name: "Hashnode", URLMain: "https://hashnode.com/", URL: "https://hashnode.com/@%s", ErrorType: "status_code"},
		{Name: "Notion", URLMain: "https://www.notion.so/", URL: "https://www.notion.so/%s", ErrorType: "status_code"},
		{Name: "Substack", URLMain: "https://substack.com/", URL: "https://%s.substack.com", ErrorType: "status_code"},
		{Name: "Telegra.ph", URLMain: "https://telegra.ph/", URL: "https://telegra.ph/%s", ErrorType: "status_code"},

		// === MISC ===
		{Name: "1x.com", URLMain: "https://1x.com/", URL: "https://1x.com/%s", ErrorType: "status_code"},
		{Name: "23andMe", URLMain: "https://www.23andme.com/", URL: "https://www.23andme.com/user/profile/%s", ErrorType: "status_code"},
		{Name: "4channel", URLMain: "https://4chan.org/", URL: "https://4chan.org/%s", ErrorType: "status_code"},
		{Name: "8tracks", URLMain: "https://8tracks.com/", URL: "https://8tracks.com/%s", ErrorType: "status_code"},
		{Name: "Capcut", URLMain: "https://www.capcut.com/", URL: "https://www.capcut.com/@%s", ErrorType: "status_code"},
		{Name: "Carrd", URLMain: "https://carrd.co/", URL: "https://carrd.co/%s", ErrorType: "status_code"},
		{Name: "Cohost", URLMain: "https://cohost.org/", URL: "https://cohost.org/%s", ErrorType: "status_code"},
		{Name: "Copy.ai", URLMain: "https://www.copy.ai/", URL: "https://www.copy.ai/%s", ErrorType: "status_code"},
		{Name: "Coupang", URLMain: "https://www.coupang.com/", URL: "https://www.coupang.com/%s", ErrorType: "status_code"},
		{Name: "Docker Hub", URLMain: "https://hub.docker.com/", URL: "https://hub.docker.com/u/%s", ErrorType: "status_code"},
		{Name: "ESPN", URLMain: "https://www.espn.com/", URL: "https://www.espn.com/espn/player/_/id/%s", ErrorType: "status_code"},
		{Name: "Eternal", URLMain: "https://eternal.gg/", URL: "https://eternal.gg/%s", ErrorType: "status_code"},
		{Name: "Fiverr", URLMain: "https://www.fiverr.com/", URL: "https://www.fiverr.com/%s", ErrorType: "status_code"},
		{Name: "Genius", URLMain: "https://genius.com/", URL: "https://genius.com/%s", ErrorType: "status_code"},
		{Name: "Habr", URLMain: "https://habr.com/", URL: "https://habr.com/ru/users/%s", ErrorType: "status_code"},
		{Name: "Hex", URLMain: "https://hex.pm/", URL: "https://hex.pm/users/%s", ErrorType: "status_code"},
		{Name: "InfoSec", URLMain: "https://infosecmachine.com/", URL: "https://infosecmachine.com/%s", ErrorType: "status_code"},
		{Name: "Kaggle", URLMain: "https://www.kaggle.com/", URL: "https://www.kaggle.com/%s", ErrorType: "status_code"},
		{Name: "Kodi", URLMain: "https://kodi.tv/", URL: "https://kodi.tv/%s", ErrorType: "status_code"},
		{Name: "Lichess", URLMain: "https://lichess.org/", URL: "https://lichess.org/@/%s", ErrorType: "status_code"},
		{Name: "Line", URLMain: "https://line.me/", URL: "https://line.me/R/ti/p/%s", ErrorType: "status_code"},
		{Name: "Linktree", URLMain: "https://linktr.ee/", URL: "https://linktr.ee/%s", ErrorType: "status_code"},
		{Name: "LiveLeak", URLMain: "https://www.liveleak.com/", URL: "https://www.liveleak.com/%s", ErrorType: "status_code"},
		{Name: "Mega", URLMain: "https://mega.nz/", URL: "https://mega.nz/%s", ErrorType: "status_code"},
		{Name: "Mozilla", URLMain: "https://www.mozilla.org/", URL: "https://www.mozilla.org/%s", ErrorType: "status_code"},
		{Name: "MyHeritage", URLMain: "https://www.myheritage.com/", URL: "https://www.myheritage.com/research?formId=master&rid=%s", ErrorType: "status_code"},
		{Name: "Piped", URLMain: "https://piped.video/", URL: "https://piped.video/channel/%s", ErrorType: "status_code"},
		{Name: "Planet Minecraft", URLMain: "https://www.planetminecraft.com/", URL: "https://www.planetminecraft.com/profile/%s", ErrorType: "status_code"},
		{Name: "Prezi", URLMain: "https://prezi.com/", URL: "https://prezi.com/p/%s", ErrorType: "status_code"},
		{Name: "Rumble", URLMain: "https://rumble.com/", URL: "https://rumble.com/user/%s", ErrorType: "status_code"},
		{Name: "Twitch", URLMain: "https://www.twitch.tv/", URL: "https://www.twitch.tv/%s", ErrorType: "status_code"},
		{Name: "Udacity", URLMain: "https://www.udacity.com/", URL: "https://www.udacity.com/%s", ErrorType: "status_code"},
		{Name: "WaniKani", URLMain: "https://www.wanikani.com/", URL: "https://www.wanikani.com/%s", ErrorType: "status_code"},
		{Name: "Waze", URLMain: "https://www.waze.com/", URL: "https://www.waze.com/%s", ErrorType: "status_code"},
		{Name: "Wish", URLMain: "https://www.wish.com/", URL: "https://www.wish.com/%s", ErrorType: "status_code"},
		{Name: "Xero", URLMain: "https://www.xero.com/", URL: "https://www.xero.com/%s", ErrorType: "status_code"},
		{Name: "Yandex", URLMain: "https://yandex.com/", URL: "https://yandex.com/%s", ErrorType: "status_code"},
		{Name: "Zenn", URLMain: "https://zenn.dev/", URL: "https://zenn.dev/%s", ErrorType: "status_code"},
	}
}
